version: "3"
services:
  proxy:
    image: nginx:stable-bullseye
    environment:
    - TARGET_SERVER=<IP_ADDRESS>
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./templates:/etc/nginx/templates
    ports:
     - "80:80"
     - "443:443"
